version: '3.2'

services:
    everybodys_got_something_to_hide:
        build: .
        volumes:
            - type: bind
              source: ./ro
              target: /home/chall/service/ro
              read_only: true
            - type: bind
              source: ./rw
              target: /home/chall/service/rw
            - type: bind
              source: ./append
              target: /home/chall/service/append
        ports:
        - 20007:6666
