version: '3.2'
services:
  yellow-submarine:
    build: .
    image: yellow_submarine
    container_name: yellow_submarine
    volumes:
      - ./ro:/home/chall/service/ro:ro
      - ./rw:/home/chall/service/rw
      - ./append:/home/chall/service/append
    ports:
      - 20001:7777
